import { fetchGenerations } from "@/api/generation";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import GenerationSkeleton from "./_components/GenerationSkeleton";

export const metadata = {
  title: "Generation - Arrax Space",
  description: "Generated by create next app",
};

const GenerationPage = async () => {
  // Get the token from the cookies
  const userId = cookies().get("arx_user_id")?.value;

  // Fetch generations by user id
  const assignments = await fetchGenerations(userId);

  return (
    <Suspense fallback={<GenerationSkeleton />}>
      <h2 className="mb-3 text-lg font-semibold md:mb-4 md:text-xl">
        Generation
      </h2>
      <Table className="rounded-lg bg-arx-black-4 shadow-lg">
        <TableHeader>
          <TableRow className="hover:bg-transparent">
            <TableHead className="text-center text-zinc-300">Level</TableHead>
            <TableHead className="text-center text-zinc-300">Total</TableHead>
            <TableHead className="text-center text-zinc-300">Active</TableHead>
            <TableHead className="text-center text-zinc-300">
              Inactive
            </TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {assignments?.levels?.map((level, index) => (
            <TableRow key={index} className="text-center hover:bg-transparent">
              <TableCell>{level?.level}</TableCell>
              <TableCell>{level?.total || 20}</TableCell>
              <TableCell>{level?.active || 20}</TableCell>
              <TableCell>{level?.inactive || 20}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Suspense>
  );
};

export default GenerationPage;
