import React from "react";
import Generation from "./_components/Generation";

export const metadata = {
  title: "Generation - Arrax Space",
  description: "Generated by create next app",
};

const GenerationPage = async () => {
  return (
    <>
      <Generation />
    </>
  );
};

export default GenerationPage;
