import React from "react";
import MatrixSlots from "./_components/MatrixSlots";

export const metadata = {
  title: "Matrix - Arrax Space",
  description: "Generated by create next app",
};

const MatrixPage = async () => {
  return (
    <>
      <MatrixSlots />
    </>
  );
};

export default MatrixPage;
