import React from "react";
import Matrix from "./_components/Matrix";

export const metadata = {
  title: "Matrix - Arrax Space",
  description: "Generated by create next app",
};

const MatrixPage = async () => {
  return (
    <>
      <Matrix />
    </>
  );
};

export default MatrixPage;
