import React from "react";
import HeroSection from "./_components/HeroSection";
import HomeFaq from "./_components/HomeFaq";
import HomeStats from "./_components/HomeStats";

export const metadata = {
  title: "Home - Arrax Space",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <>
      <HeroSection />
      <HomeStats />
      <HomeFaq />
    </>
  );
};

export default HomePage;
