import Container from "@/components/ui/Container";
import React from "react";
import LoginRegisterComp from "./_components/LoginRegisterComp";

export const metadata = {
  title: "Login - Arrax Space",
  description: "Generated by create next app",
};

const LoginPage = ({ searchParams }) => {
  return (
    <div className="flex min-h-[90vh] items-center justify-between bg-arx-black-5">
      <Container>
        <LoginRegisterComp referredBy={searchParams.ref} />
      </Container>
    </div>
  );
};

export default LoginPage;
