import { Button } from "@/components/ui/button";
import Container from "@/components/ui/Container";
import React from "react";
import AutomaticLoginForm from "./_components/AutomaticLoginForm";
import RegisterForm from "./_components/RegisterForm";

export const metadata = {
  title: "Login - Arrax Space",
  description: "Generated by create next app",
};

const LoginPage = () => {
  return (
    <div className="flex min-h-[90vh] items-center justify-between bg-gradient-to-br from-gray-800 to-black">
      <Container>
        <div className="mx-auto flex w-full flex-col shadow-lg md:flex-row">
          {/* Registration Section */}
          <div className="w-full rounded-l-lg bg-[#1a1a1a] p-7 md:w-1/2 md:p-9">
            <h2 className="text-custom-style mb-4 text-lg font-semibold md:mb-5 md:text-2xl md:font-bold">
              Get Started with Arrax Space
            </h2>
            {/* <p className="mb-6 text-sm">
              Please double-check the Inviter&apos;s ID before registering.
            </p> */}
            <div className="mb-3 md:mb-5">
              <Button variant="secondary" className="w-full">
                Connect Wallet
              </Button>
            </div>
            {/* register form */}
            <RegisterForm />
          </div>

          {/* Login Section */}
          <div className="w-full rounded-r-lg bg-slate-900 p-7 md:w-1/2 md:p-9">
            <h2 className="text-custom-style mb-4 text-lg font-semibold md:mb-5 md:text-2xl md:font-bold">
              Login to Your Personal Account
            </h2>
            {/* login form */}
            <AutomaticLoginForm />
            {/* <p className="mt-4 text-xs text-gray-400">
              To access all the functions of your personal account, use
              auto-login.
            </p> */}
          </div>
        </div>
      </Container>
    </div>
  );
};

export default LoginPage;
