import React from "react";
import ProfileOverview from "./_components/ProfileOverview";

export const metadata = {
  title: "Profile - Arrax Space",
  description: "Generated by create next app",
};

const ProfilePage = () => {
  return (
    <div>
      <ProfileOverview />
    </div>
  );
};

export default ProfilePage;
