import React from "react";
import UserDetails from "./_components/UserDetails";

export const metadata = {
  title: "User Details - Arrax Space",
  description: "Generated by create next app",
};

const UserDetailsPage = ({ params }) => {
  return (
    <>
      <UserDetails slug={params?.slug} />
    </>
  );
};

export default UserDetailsPage;
