import React from "react";

export const metadata = {
  title: "Settings - Arrax Space",
  description: "Generated by create next app",
};

const SettingsPage = () => {
  return (
    <div>
      <p>
        Settings page.
        {/* Admin roles er jonne arekta option thakbe, Settings eikhane 2ta Toggle
        Button thakbe,, akta 1. Slot purchase on/off 2. Registration on/off */}
      </p>
    </div>
  );
};

export default SettingsPage;
