import React from "react";
import ToggleCard from "./_components/ToggleCard";

export const metadata = {
  title: "Settings - Arrax Space",
  description: "Generated by create next app",
};

const SettingsPage = () => {
  return (
    <div className="flex min-h-[70vh] flex-col items-center justify-center">
      {/* title */}
      <h2 className="mb-3 text-xl font-semibold text-gray-100 md:mb-4 md:text-2xl">
        Settings
      </h2>

      {/* toggle card */}
      <ToggleCard />
    </div>
  );
};

export default SettingsPage;
