// Contract configuration
export const CONTRACT_CONFIG = {
  REGISTRATION_ADDRESS: process.env.NEXT_PUBLIC_REGISTRATION_CONTRACT_ADDRESS,
  TOKEN_ADDRESS: process.env.NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS,
  RPC_URL: process.env.NEXT_PUBLIC_RPC_URL
};