import React from "react";
import ManageUsers from "./_components/ManageUsers";

export const metadata = {
  title: "Manage Users - Arrax Space",
  description: "Generated by create next app",
};

const ManageUsersPage = () => {
  return (
    <>
      <ManageUsers />
    </>
  );
};

export default ManageUsersPage;
