import React from "react";
import DashboardOverview from "./_components/DashboardOverview";

export const metadata = {
  title: "Dashboard - Arrax Space",
  description: "Generated by create next app",
};

const DashboardHomePage = () => {
  return (
    <div>
      <DashboardOverview />
    </div>
  );
};

export default DashboardHomePage;
